### ISSUE TITLE
Unable to get started with the README instructions

### ISSUE THREAD

**Issue by talentedunicorn** [craigharman/keystone6-documentreader-vue#1]
I'd like to start by saying thank you for making a vue document renderer for Keystone 🙌 
I was following the README guide to use your component in a vue-cli app and was stuck on the `import` bit... 
```
import DocumentReader from "~/components/KeystoneDocument/Document";
```
but managed to do 
```
import KeystoneDocument from 'keystone6-documentreader-vue/src'
```

Was this something I should be doing and should the README get updated?
Thanks again.

**Comment by craigharman** [comment]
My apologies, I wrote all this up and then had terrible issues trying to compile a node package due to Vue's handling of JSX I believe. I'm glad you got it going using the import. I'll update the readmne and create an issue/request here to get someone to assist with creating the package properly.
